import type { Metadata } from "next";
import { Averia_Serif_Libre, Inter } from "next/font/google";
import "./globals.css";

const averiaSerif = Averia_Serif_Libre({
  variable: "--font-averia-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pitada",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${averiaSerif.variable} ${inter.variable} antialiased bg-bg`}
        data-theme="light"
      >
        {children}
      </body>
    </html>
  );
}
